#include <iostream>
      #include <fstream>
  #include <string>
          #include <vector>
#define Z_OVOSCH std
    #define _ string
#define GLAVNIY_V_HATE main
      #define GOLDA cout
  #define AMERIKA endl
#define BABKI long long
    #define IHOR int
#define MELOCH short
      #define BUKVA char
  #define KRUGOM_MARSH for
#define STOYAT_BOYATSJA while
    #define JA_RUSSKIY if
#define PINDOS else
      #define ZAHODI_NE_BOYSJA {
  #define UHODI_NE_PLACH }
#define NA_POSOSHOK ;
    #define V_DUSHU <<
#define IZ_DUSHI >>
      #define OTYAL =
  #define NE_VERYU ==
#define BRAT_MOY !=
    #define NAKATIM ++
#define RAZMERCHIK length
      #define DOMOY return
  #define OTKRYVASHKA open
#define ZAKRYVASHKA close
    #define ZERO (1945-1945)
#define ODIN_V_POLE_VOIN (1000-999)
      #define PARA (1+1)
  #define CHERT_LYSYI %
#define BAZA [
    #define KRYSHA ]
#define FEDORA_LINUX (
      #define BOGOPODOBNIY_ARCH )

IHOR GLAVNIY_V_HATE FEDORA_LINUX BOGOPODOBNIY_ARCH ZAHODI_NE_BOYSJA Z_OVOSCH::ifstream 
spion FEDORA_LINUX "napisy.txt" BOGOPODOBNIY_ARCH NA_POSOSHOK MELOCH ded_maxim OTYAL 
ZERO NA_POSOSHOK Z_OVOSCH::_ shishka OTYAL "a) Podaj, ile " NA_POSOSHOK MELOCH 
babka_zina OTYAL ZERO NA_POSOSHOK Z_OVOSCH::ofstream stukach FEDORA_LINUX 
"zadanie4.txt" BOGOPODOBNIY_ARCH NA_POSOSHOK MELOCH kot_boris OTYAL ZERO NA_POSOSHOK 
Z_OVOSCH::_ elka OTYAL "jest napisow " NA_POSOSHOK MELOCH pes_sharik OTYAL ZERO 
NA_POSOSHOK JA_RUSSKIY FEDORA_LINUX !spion.is_open FEDORA_LINUX BOGOPODOBNIY_ARCH 
BOGOPODOBNIY_ARCH ZAHODI_NE_BOYSJA Z_OVOSCH::GOLDA V_DUSHU "GDE FAIL SUKA?" V_DUSHU 
Z_OVOSCH::AMERIKA NA_POSOSHOK DOMOY -1 NA_POSOSHOK UHODI_NE_PLACH Z_OVOSCH::_ penek 
OTYAL "o parzystej dlugosci: " NA_POSOSHOK BABKI garazh BAZA 30 KRYSHA OTYAL 
ZAHODI_NE_BOYSJA ZERO UHODI_NE_PLACH NA_POSOSHOK Z_OVOSCH::_ beriozka OTYAL 
"\nb) Podaj, ile " NA_POSOSHOK Z_OVOSCH::_ medved OTYAL ", ktore zawieraja taka sama liczbe zer i jedynek: " 
NA_POSOSHOK Z_OVOSCH::_ topol OTYAL "\nc) Podaj, ile " NA_POSOSHOK Z_OVOSCH::_ 
kontrabanda NA_POSOSHOK Z_OVOSCH::_ ivan_chai OTYAL "skladajacych sie z samych zer: " 
NA_POSOSHOK STOYAT_BOYATSJA FEDORA_LINUX spion IZ_DUSHI kontrabanda BOGOPODOBNIY_ARCH 
ZAHODI_NE_BOYSJA IHOR noliki OTYAL ZERO, edinichki OTYAL ZERO NA_POSOSHOK KRUGOM_MARSH 
FEDORA_LINUX auto patron : kontrabanda BOGOPODOBNIY_ARCH ZAHODI_NE_BOYSJA JA_RUSSKIY 
FEDORA_LINUX patron NE_VERYU '0' BOGOPODOBNIY_ARCH noliki NAKATIM NA_POSOSHOK PINDOS 
edinichki NAKATIM NA_POSOSHOK UHODI_NE_PLACH JA_RUSSKIY FEDORA_LINUX 
kontrabanda.RAZMERCHIK FEDORA_LINUX BOGOPODOBNIY_ARCH CHERT_LYSYI PARA NE_VERYU ZERO 
BOGOPODOBNIY_ARCH ded_maxim NAKATIM NA_POSOSHOK JA_RUSSKIY FEDORA_LINUX noliki NE_VERYU 
edinichki BOGOPODOBNIY_ARCH babka_zina NAKATIM NA_POSOSHOK JA_RUSSKIY FEDORA_LINUX 
noliki NE_VERYU kontrabanda.RAZMERCHIK FEDORA_LINUX BOGOPODOBNIY_ARCH 
BOGOPODOBNIY_ARCH kot_boris NAKATIM NA_POSOSHOK JA_RUSSKIY FEDORA_LINUX edinichki 
NE_VERYU kontrabanda.RAZMERCHIK FEDORA_LINUX BOGOPODOBNIY_ARCH BOGOPODOBNIY_ARCH 
pes_sharik NAKATIM NA_POSOSHOK FEDORA_LINUX kontrabanda.RAZMERCHIK FEDORA_LINUX 
BOGOPODOBNIY_ARCH BOGOPODOBNIY_ARCH BAZA garazh KRYSHA NAKATIM NA_POSOSHOK 
UHODI_NE_PLACH Z_OVOSCH::_ samovar OTYAL "oraz podaj, ile " NA_POSOSHOK Z_OVOSCH::_ 
garmoshka OTYAL "skladajacych sie z samych jedynek: " NA_POSOSHOK stukach V_DUSHU 
shishka V_DUSHU elka V_DUSHU penek V_DUSHU ded_maxim V_DUSHU Z_OVOSCH::AMERIKA 
NA_POSOSHOK Z_OVOSCH::GOLDA V_DUSHU shishka V_DUSHU elka V_DUSHU penek V_DUSHU 
ded_maxim V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK stukach V_DUSHU beriozka V_DUSHU elka 
V_DUSHU medved V_DUSHU babka_zina V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK Z_OVOSCH::
GOLDA V_DUSHU beriozka V_DUSHU elka V_DUSHU medved V_DUSHU babka_zina V_DUSHU 
Z_OVOSCH::AMERIKA NA_POSOSHOK stukach V_DUSHU topol V_DUSHU elka V_DUSHU ivan_chai 
V_DUSHU kot_boris V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK stukach V_DUSHU samovar 
V_DUSHU elka V_DUSHU garmoshka V_DUSHU pes_sharik V_DUSHU Z_OVOSCH::AMERIKA 
NA_POSOSHOK Z_OVOSCH::GOLDA V_DUSHU topol V_DUSHU elka V_DUSHU ivan_chai V_DUSHU 
kot_boris V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK Z_OVOSCH::GOLDA V_DUSHU samovar 
V_DUSHU elka V_DUSHU garmoshka V_DUSHU pes_sharik V_DUSHU Z_OVOSCH::AMERIKA 
NA_POSOSHOK stukach V_DUSHU "\nd) " V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK Z_OVOSCH::
GOLDA V_DUSHU "\nd) " V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK KRUGOM_MARSH 
FEDORA_LINUX BUKVA matreshka OTYAL PARA NA_POSOSHOK matreshka <= 16 NA_POSOSHOK 
matreshka NAKATIM BOGOPODOBNIY_ARCH ZAHODI_NE_BOYSJA stukach V_DUSHU "dlugosc " 
V_DUSHU FEDORA_LINUX IHOR BOGOPODOBNIY_ARCH matreshka V_DUSHU ": " V_DUSHU matreshka 
BAZA garazh KRYSHA V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK Z_OVOSCH::GOLDA V_DUSHU 
"dlugosc " V_DUSHU FEDORA_LINUX IHOR BOGOPODOBNIY_ARCH matreshka V_DUSHU ": " V_DUSHU 
matreshka BAZA garazh KRYSHA V_DUSHU Z_OVOSCH::AMERIKA NA_POSOSHOK UHODI_NE_PLACH 
spion.ZAKRYVASHKA FEDORA_LINUX BOGOPODOBNIY_ARCH NA_POSOSHOK stukach.ZAKRYVASHKA 
FEDORA_LINUX BOGOPODOBNIY_ARCH NA_POSOSHOK Z_OVOSCH::GOLDA V_DUSHU "KOGDA SDAL KR" 
NA_POSOSHOK DOMOY ZERO NA_POSOSHOK UHODI_NE_PLACH
